nodeLinker: node-modules

npmAuthToken: "${NPM_AUTH_TOKEN:-fallback}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs
