plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs

npmAuthToken: "${NPM_AUTH_TOKEN:-fallback}"

packageExtensions:
  "@storybook/addon-console@*":
    dependencies:
      prop-types: "*"
